// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: service.proto
#ifndef GRPC_service_2eproto__INCLUDED
#define GRPC_service_2eproto__INCLUDED

#include "service.pb.h"

#include <functional>
#include <grpc/impl/codegen/port_platform.h>
#include <grpcpp/impl/codegen/async_generic_service.h>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/client_context.h>
#include <grpcpp/impl/codegen/completion_queue.h>
#include <grpcpp/impl/codegen/message_allocator.h>
#include <grpcpp/impl/codegen/method_handler.h>
#include <grpcpp/impl/codegen/proto_utils.h>
#include <grpcpp/impl/codegen/rpc_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/impl/codegen/server_context.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/status.h>
#include <grpcpp/impl/codegen/stub_options.h>
#include <grpcpp/impl/codegen/sync_stream.h>

namespace photon_dance_snowflake_service {

class PhotonDanceSnowflakeService final {
 public:
  static constexpr char const* service_full_name() {
    return "photon_dance_snowflake_service.PhotonDanceSnowflakeService";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    virtual ::grpc::Status GetUUID(::grpc::ClientContext* context, const ::photon_dance_snowflake_service::PhotonDanceSnowflakeServiceRequest& request, ::photon_dance_snowflake_service::PhotonDanceSnowflakeServiceResponse* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::photon_dance_snowflake_service::PhotonDanceSnowflakeServiceResponse>> AsyncGetUUID(::grpc::ClientContext* context, const ::photon_dance_snowflake_service::PhotonDanceSnowflakeServiceRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::photon_dance_snowflake_service::PhotonDanceSnowflakeServiceResponse>>(AsyncGetUUIDRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::photon_dance_snowflake_service::PhotonDanceSnowflakeServiceResponse>> PrepareAsyncGetUUID(::grpc::ClientContext* context, const ::photon_dance_snowflake_service::PhotonDanceSnowflakeServiceRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::photon_dance_snowflake_service::PhotonDanceSnowflakeServiceResponse>>(PrepareAsyncGetUUIDRaw(context, request, cq));
    }
    class experimental_async_interface {
     public:
      virtual ~experimental_async_interface() {}
      virtual void GetUUID(::grpc::ClientContext* context, const ::photon_dance_snowflake_service::PhotonDanceSnowflakeServiceRequest* request, ::photon_dance_snowflake_service::PhotonDanceSnowflakeServiceResponse* response, std::function<void(::grpc::Status)>) = 0;
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      virtual void GetUUID(::grpc::ClientContext* context, const ::photon_dance_snowflake_service::PhotonDanceSnowflakeServiceRequest* request, ::photon_dance_snowflake_service::PhotonDanceSnowflakeServiceResponse* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      #else
      virtual void GetUUID(::grpc::ClientContext* context, const ::photon_dance_snowflake_service::PhotonDanceSnowflakeServiceRequest* request, ::photon_dance_snowflake_service::PhotonDanceSnowflakeServiceResponse* response, ::grpc::experimental::ClientUnaryReactor* reactor) = 0;
      #endif
    };
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    typedef class experimental_async_interface async_interface;
    #endif
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    async_interface* async() { return experimental_async(); }
    #endif
    virtual class experimental_async_interface* experimental_async() { return nullptr; }
  private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::photon_dance_snowflake_service::PhotonDanceSnowflakeServiceResponse>* AsyncGetUUIDRaw(::grpc::ClientContext* context, const ::photon_dance_snowflake_service::PhotonDanceSnowflakeServiceRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::photon_dance_snowflake_service::PhotonDanceSnowflakeServiceResponse>* PrepareAsyncGetUUIDRaw(::grpc::ClientContext* context, const ::photon_dance_snowflake_service::PhotonDanceSnowflakeServiceRequest& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel);
    ::grpc::Status GetUUID(::grpc::ClientContext* context, const ::photon_dance_snowflake_service::PhotonDanceSnowflakeServiceRequest& request, ::photon_dance_snowflake_service::PhotonDanceSnowflakeServiceResponse* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::photon_dance_snowflake_service::PhotonDanceSnowflakeServiceResponse>> AsyncGetUUID(::grpc::ClientContext* context, const ::photon_dance_snowflake_service::PhotonDanceSnowflakeServiceRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::photon_dance_snowflake_service::PhotonDanceSnowflakeServiceResponse>>(AsyncGetUUIDRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::photon_dance_snowflake_service::PhotonDanceSnowflakeServiceResponse>> PrepareAsyncGetUUID(::grpc::ClientContext* context, const ::photon_dance_snowflake_service::PhotonDanceSnowflakeServiceRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::photon_dance_snowflake_service::PhotonDanceSnowflakeServiceResponse>>(PrepareAsyncGetUUIDRaw(context, request, cq));
    }
    class experimental_async final :
      public StubInterface::experimental_async_interface {
     public:
      void GetUUID(::grpc::ClientContext* context, const ::photon_dance_snowflake_service::PhotonDanceSnowflakeServiceRequest* request, ::photon_dance_snowflake_service::PhotonDanceSnowflakeServiceResponse* response, std::function<void(::grpc::Status)>) override;
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      void GetUUID(::grpc::ClientContext* context, const ::photon_dance_snowflake_service::PhotonDanceSnowflakeServiceRequest* request, ::photon_dance_snowflake_service::PhotonDanceSnowflakeServiceResponse* response, ::grpc::ClientUnaryReactor* reactor) override;
      #else
      void GetUUID(::grpc::ClientContext* context, const ::photon_dance_snowflake_service::PhotonDanceSnowflakeServiceRequest* request, ::photon_dance_snowflake_service::PhotonDanceSnowflakeServiceResponse* response, ::grpc::experimental::ClientUnaryReactor* reactor) override;
      #endif
     private:
      friend class Stub;
      explicit experimental_async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class experimental_async_interface* experimental_async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class experimental_async async_stub_{this};
    ::grpc::ClientAsyncResponseReader< ::photon_dance_snowflake_service::PhotonDanceSnowflakeServiceResponse>* AsyncGetUUIDRaw(::grpc::ClientContext* context, const ::photon_dance_snowflake_service::PhotonDanceSnowflakeServiceRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::photon_dance_snowflake_service::PhotonDanceSnowflakeServiceResponse>* PrepareAsyncGetUUIDRaw(::grpc::ClientContext* context, const ::photon_dance_snowflake_service::PhotonDanceSnowflakeServiceRequest& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_GetUUID_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    virtual ::grpc::Status GetUUID(::grpc::ServerContext* context, const ::photon_dance_snowflake_service::PhotonDanceSnowflakeServiceRequest* request, ::photon_dance_snowflake_service::PhotonDanceSnowflakeServiceResponse* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_GetUUID : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_GetUUID() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_GetUUID() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetUUID(::grpc::ServerContext* /*context*/, const ::photon_dance_snowflake_service::PhotonDanceSnowflakeServiceRequest* /*request*/, ::photon_dance_snowflake_service::PhotonDanceSnowflakeServiceResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestGetUUID(::grpc::ServerContext* context, ::photon_dance_snowflake_service::PhotonDanceSnowflakeServiceRequest* request, ::grpc::ServerAsyncResponseWriter< ::photon_dance_snowflake_service::PhotonDanceSnowflakeServiceResponse>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_GetUUID<Service > AsyncService;
  template <class BaseClass>
  class ExperimentalWithCallbackMethod_GetUUID : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    ExperimentalWithCallbackMethod_GetUUID() {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::Service::
    #else
      ::grpc::Service::experimental().
    #endif
        MarkMethodCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::photon_dance_snowflake_service::PhotonDanceSnowflakeServiceRequest, ::photon_dance_snowflake_service::PhotonDanceSnowflakeServiceResponse>(
            [this](
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
                   ::grpc::CallbackServerContext*
    #else
                   ::grpc::experimental::CallbackServerContext*
    #endif
                     context, const ::photon_dance_snowflake_service::PhotonDanceSnowflakeServiceRequest* request, ::photon_dance_snowflake_service::PhotonDanceSnowflakeServiceResponse* response) { return this->GetUUID(context, request, response); }));}
    void SetMessageAllocatorFor_GetUUID(
        ::grpc::experimental::MessageAllocator< ::photon_dance_snowflake_service::PhotonDanceSnowflakeServiceRequest, ::photon_dance_snowflake_service::PhotonDanceSnowflakeServiceResponse>* allocator) {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(0);
    #else
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::experimental().GetHandler(0);
    #endif
      static_cast<::grpc::internal::CallbackUnaryHandler< ::photon_dance_snowflake_service::PhotonDanceSnowflakeServiceRequest, ::photon_dance_snowflake_service::PhotonDanceSnowflakeServiceResponse>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~ExperimentalWithCallbackMethod_GetUUID() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetUUID(::grpc::ServerContext* /*context*/, const ::photon_dance_snowflake_service::PhotonDanceSnowflakeServiceRequest* /*request*/, ::photon_dance_snowflake_service::PhotonDanceSnowflakeServiceResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    virtual ::grpc::ServerUnaryReactor* GetUUID(
      ::grpc::CallbackServerContext* /*context*/, const ::photon_dance_snowflake_service::PhotonDanceSnowflakeServiceRequest* /*request*/, ::photon_dance_snowflake_service::PhotonDanceSnowflakeServiceResponse* /*response*/)
    #else
    virtual ::grpc::experimental::ServerUnaryReactor* GetUUID(
      ::grpc::experimental::CallbackServerContext* /*context*/, const ::photon_dance_snowflake_service::PhotonDanceSnowflakeServiceRequest* /*request*/, ::photon_dance_snowflake_service::PhotonDanceSnowflakeServiceResponse* /*response*/)
    #endif
      { return nullptr; }
  };
  #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
  typedef ExperimentalWithCallbackMethod_GetUUID<Service > CallbackService;
  #endif

  typedef ExperimentalWithCallbackMethod_GetUUID<Service > ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_GetUUID : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_GetUUID() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_GetUUID() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetUUID(::grpc::ServerContext* /*context*/, const ::photon_dance_snowflake_service::PhotonDanceSnowflakeServiceRequest* /*request*/, ::photon_dance_snowflake_service::PhotonDanceSnowflakeServiceResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_GetUUID : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_GetUUID() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_GetUUID() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetUUID(::grpc::ServerContext* /*context*/, const ::photon_dance_snowflake_service::PhotonDanceSnowflakeServiceRequest* /*request*/, ::photon_dance_snowflake_service::PhotonDanceSnowflakeServiceResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestGetUUID(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class ExperimentalWithRawCallbackMethod_GetUUID : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    ExperimentalWithRawCallbackMethod_GetUUID() {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::Service::
    #else
      ::grpc::Service::experimental().
    #endif
        MarkMethodRawCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
                   ::grpc::CallbackServerContext*
    #else
                   ::grpc::experimental::CallbackServerContext*
    #endif
                     context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->GetUUID(context, request, response); }));
    }
    ~ExperimentalWithRawCallbackMethod_GetUUID() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetUUID(::grpc::ServerContext* /*context*/, const ::photon_dance_snowflake_service::PhotonDanceSnowflakeServiceRequest* /*request*/, ::photon_dance_snowflake_service::PhotonDanceSnowflakeServiceResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    virtual ::grpc::ServerUnaryReactor* GetUUID(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)
    #else
    virtual ::grpc::experimental::ServerUnaryReactor* GetUUID(
      ::grpc::experimental::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)
    #endif
      { return nullptr; }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_GetUUID : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_GetUUID() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler<
          ::photon_dance_snowflake_service::PhotonDanceSnowflakeServiceRequest, ::photon_dance_snowflake_service::PhotonDanceSnowflakeServiceResponse>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::photon_dance_snowflake_service::PhotonDanceSnowflakeServiceRequest, ::photon_dance_snowflake_service::PhotonDanceSnowflakeServiceResponse>* streamer) {
                       return this->StreamedGetUUID(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_GetUUID() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status GetUUID(::grpc::ServerContext* /*context*/, const ::photon_dance_snowflake_service::PhotonDanceSnowflakeServiceRequest* /*request*/, ::photon_dance_snowflake_service::PhotonDanceSnowflakeServiceResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedGetUUID(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::photon_dance_snowflake_service::PhotonDanceSnowflakeServiceRequest,::photon_dance_snowflake_service::PhotonDanceSnowflakeServiceResponse>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_GetUUID<Service > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_GetUUID<Service > StreamedService;
};

}  // namespace photon_dance_snowflake_service


#endif  // GRPC_service_2eproto__INCLUDED
